markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: "TeX"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
theme: minima
# Site title
site.title: "Inverse problems and uncertainty quantification for the control of dynamical systems"